### ISSUE TITLE
Tasks undefined

### ISSUE THREAD

**Issue by cahir1987** [custom-components/grocy#191] opened 2022-02-24 13:50 UTC
## Unless all relevant information is provided, I can't help you

**Describe the bug**
Tasks not showing in hassio. 

Chores works fine
Tasks shows undefined

**What is your installed versions of Home Assistant, Grocy and this integration?**

Home Assistant 2022.2.8
Grocy 0.16.0

**How do you have Grocy installed? Add-on or external?**

Add-on

**Have you added debugging to the log, and what does the log say?**

Logger: custom_components.grocy
Source: custom_components/grocy/__init__.py:104
Integration: Grocy ([documentation](https://github.com/custom-components/grocy), [issues](https://github.com/custom-components/grocy/issues))
First occurred: 13:56:12 (170 occurrences)
Last logged: 14:41:04

Update of Overdue_tasks failed with 1 validation error for TaskResponse due_date invalid date format (type=value_error.date)
Update of Tasks failed with 1 validation error for TaskResponse due_date invalid date format (type=value_error.date)
Update of Overdue_tasks failed with 1 validation error for TaskResponse category_id value is not a valid integer (type=type_error.integer)
Update of Tasks failed with 1 validation error for TaskResponse category_id value is not a valid integer (type=type_error.integer)

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**

**Comment by dakoellis** [comment] 2022-03-07 04:12
I had the same issue but updating to Home Assistant 2022.3.2 and the latest grocy image/addon fixed it for me

**Comment by dakoellis** [comment] 2022-04-29 15:43
@rum0s  You need to update your grocy integration. 4.2.0b is out

**Comment by rum0s** [comment] 2022-04-29 16:36
@dakoellis Thank you very much! Can you give me a hint how I can manually update? 4.2.0b seems to be a pre-release and I don't no how to choose the version when installing the integration.

besides, adding product and task categories helped somehow.

**Comment by dakoellis** [comment] 2022-04-29 21:48
> @dakoellis Thank you very much! I'll give it a try
> 
> besides, adding product and task categories helped somehow.

I'm using hacs so it just popped up for me. Otherwise you would need to copy the contents of the release to the custom components directory on your hass server

**Comment by rum0s** [comment] 2022-05-01 11:25
I activated the beta and installed 4.2.0b but the problem still persists. 

If there is no product group / task group or task assigned to a user it throws an error. Is this the intended behaviour?

**Closed** 2022-05-21 19:55 UTC
Labels: bug, pygrocy-bug
