### ISSUE TITLE
Chore error after HA upgrade

### ISSUE THREAD

**Issue by cyberfly79** [custom-components/grocy#129] opened 2021-04-13 10:15 UTC
## Unless all relevant information is provided, I can't help you

**Describe the bug**
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/grocy/services.py, line 191: coordinator.api.execute_chore(chore_id, done_by, tracked_time)

Home Assistant 2021.4.3
Grocy custom component v3.0.1
Lovelace Grocy Chores Card v2.1.0

**Expected behavior**
If I did my chore, I get an error clicking the button.

**To Reproduce**

**What is your installed versions of Home Assistant, Grocy and this integration?**

**How do you have Grocy installed? Add-on or external?**

**Have you added debugging to the log, and what does the log say?**

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**

**Comment by isabellaalstrom** [comment] 2021-04-13 10:26
duplicate of #121, fix released soon, in beta

**Closed by isabellaalstrom** 2021-04-13 10:26 UTC
