### ISSUE TITLE
Error when trying to consume product item from Home Assistant UI

### ISSUE THREAD

**Issue by spaminna** [custom-components/grocy#122] opened 2021-04-10 06:49 UTC
**Describe the bug**
Get an error in Home assistant when trying to consume a product. I have tried to track it from button card in lovelace and using the service call **grocy.consume_product_from_stock** from dev tools. The error I get is the same.

**Expected behavior**
I expected the consumption to be written in grocy. Just an error is displayed, nothing is updated in Grocy.

**To Reproduce**
HA menu / Develeper Tools
```
service: grocy.consume_product_from_stock
data:
  product_id: 1
  amount: 1
  transaction_type: CONSUME
```

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant 2021.4.1
Grocy: 3.0.1 (add-on: 0.12.0)
Integration: 3.0.1

**How do you have Grocy installed? Add-on or external?**
 Add-on
**Have you added debugging to the log, and what does the log say?**
`2021-04-10 08:45:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140529203545472] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 96, in async_call_grocy_service
    await async_consume_product_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 176, in async_consume_product_service
    coordinator.api.consume_product(
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 123, in consume_product
    return self._api_client.consume_product(
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 651, in consume_product
    self._do_post_request(f"stock/products/{product_id}/consume", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 557, in _do_post_request
    resp = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/grocy/services.py, line 176: coordinator.api.consume_product(
2021-04-10 08:45:27 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 0.244 seconds
`

**Additional context**
I also reinstalled the Grocy add-on plugin + HACS Grocy Custom component plugin (2 times).

**Comment by isabellaalstrom** [comment] 2021-04-10 06:56
I will try to fix this as soon as I can, but right now I have some family things that unfortunately makes me not being able to do this right at this moment.

**Comment by ludeeus** [comment] 2021-04-11 10:42
Duplicate of #121

**Closed** 2021-04-11 12:12 UTC
Labels: bug, help wanted

**Comment by isabellaalstrom** [comment] 2021-04-13 09:14
@spaminna  Could you please try the latest beta?

**Comment by spaminna** [comment] 2021-04-22 13:23
> @spaminna Could you please try the latest beta?

It works :) Thx for fast repair.
